name: signko_app
description: "Bidirectional Filipino Sign Language Translation System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Bluetooth Low Energy
  flutter_blue_plus: ^1.31.14
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Video Rendering
  video_player: ^2.8.2
  
  # STT and TTS
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  
  # UI and Utilities
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
